project_id = "asqdfrzhakgnlfhnzfyu"

[functions.process-email-queue]
verify_jwt = true

[functions.email-track-click]
verify_jwt = false

[functions.email-track-open]
verify_jwt = false

[functions.booking-ics]
verify_jwt = false

[functions.email-imap-smtp-connect]
verify_jwt = false

[functions.email-imap-smtp-send]
verify_jwt = false
